security:
    providers:
        in_memory:
            memory:
                users:
                    tom:
                        password: 1234
                        roles: 'ROLE_USER'
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'
                    super:
                        password: 1234
                        roles: 'ROLE_SUPER_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin/faktury, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]